### ISSUE TITLE
Active Maintainer confusion

### ISSUE THREAD

**Issue by rhass** [jeroenj/sonarr-cookbook#3]
The marketplace directs the Sonarr cookbook to here: https://github.com/jamesconant/sonarr-cookbook

However, the fork does not have Issues available and my PR seems to have stagnated.

Which repo is the correct one? Please let me know if either of you want an additional maintainer.  =)

As a side note, Radarr is seems to be nearly identical for installation and configuration. It may make sense to turn this cookbook into a custom resource which can be use to install and configure either one -- but I am not sure how much effort that will be just yet.

**Comment by jeroenj** [comment]
@jamesconant adopted it some time ago as I'm no longer using this. It would be best to get in touch with him if you're interested into maintaining it. :)
